OsqpEigen::Solver Class Reference
Solver class is a wrapper of the OSQP OSQPWorkspace struct.
#include <Solver.hpp>
Public Member Functions
Solver ()
Constructor.
~Solver ()
Deconstructor.
bool initSolver ()
Initialize the solver with the actual initial data and settings.
bool isInitialized ()
Check if the solver is initialized.
void clearSolver ()
Dealocate memory.
bool clearSolverVariables ()
Set to zero all the solver variables.
bool solve ()
Solve the QP optimization problem.
const Eigen::VectorXd & getSolution ()
Get the optimization problem solution.
template<int n>
bool updateGradient (Eigen::Matrix< c_float, n, 1 > &gradient)
Update the linear part of the cost function (Gradient).
bool updateGradient (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> &gradient)
Update the linear part of the cost function (Gradient).
template<int m>
bool updateLowerBound (Eigen::Matrix< c_float, m, 1 > &lowerBound)
Update the lower bounds limit (size m).
bool updateLowerBound (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> &lowerBound)
Update the lower bounds limit (size m).
template<int m>
bool updateUpperBound (Eigen::Matrix< c_float, m, 1 > &upperBound)
Update the upper bounds limit (size m).
bool updateUpperBound (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> &upperBound)
Update the upper bounds limit (size m).
template<int m>
bool updateBounds (Eigen::Matrix< c_float, m, 1 > &lowerBound, Eigen::Matrix< c_float, m, 1 > &upperBound)
Update both upper and lower bounds (size m).
bool updateBounds (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> &lowerBound, const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> &upperBound)
Update both upper and lower bounds (size m).
template<typename T >
bool updateHessianMatrix (const Eigen::SparseMatrix< T > &hessianMatrix)
Update the quadratic part of the cost function (Hessian).
template<typename Derived >
bool updateHessianMatrix (const Eigen::SparseCompressedBase< Derived > &hessianMatrix)
Update the quadratic part of the cost function (Hessian).
template<typename T >
bool updateLinearConstraintsMatrix (const Eigen::SparseMatrix< T > &linearConstraintsMatrix)
Update the linear constraints matrix (A)
template<typename Derived >
bool updateLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > &linearConstraintsMatrix)
Update the linear constraints matrix (A)
template<typename T , int n, int m>
bool setWarmStart (const Eigen::Matrix< T, n, 1 > &primalVariable, const Eigen::Matrix< T, m, 1 > &dualVariable)
Set the entire.
template<typename T , int n>
bool setPrimalVariable (const Eigen::Matrix< T, n, 1 > &primalVariable)
template<typename T , int m>
bool setDualVariable (const Eigen::Matrix< T, m, 1 > &dualVariable)
template<typename T , int n>
bool getPrimalVariable (Eigen::Matrix< T, n, 1 > &primalVariable)
template<typename T , int m>
bool getDualVariable (Eigen::Matrix< T, m, 1 > &dualVariable)
const std::unique_ptr< OsqpEigen::Settings > & settings () const
Get the solver settings pointer.
const std::unique_ptr< OsqpEigen::Data > & data () const
Get the pointer to the solver initial data.
Detailed Description
Solver class is a wrapper of the OSQP OSQPWorkspace struct.
Definition at line 32 of file Solver.hpp.
Member Function Documentation
clearSolverVariables()
bool OsqpEigen::Solver::clearSolverVariables ()
Set to zero all the solver variables.
Returns
true/false in case of success/failure.
Definition at line 26 of file Solver.cpp.
data()
const std::unique_ptr< OsqpEigen::Data > & OsqpEigen::Solver::data () const
Get the pointer to the solver initial data.
Returns
the pointer to Data object.
Definition at line 146 of file Solver.cpp.
getSolution()
const Eigen::VectorXd & OsqpEigen::Solver::getSolution ()
Get the optimization problem solution.
Returns
an Eigen::Vector contating the optimization result.
Definition at line 132 of file Solver.cpp.
initSolver()
bool OsqpEigen::Solver::initSolver ()
Initialize the solver with the actual initial data and settings.
Returns
true/false in case of success/failure.
Definition at line 66 of file Solver.cpp.
Referenced by updateHessianMatrix().
isInitialized()
bool OsqpEigen::Solver::isInitialized ()
Check if the solver is initialized.
Returns
true if the solver is initialized.
Definition at line 93 of file Solver.cpp.
settings()
const std::unique_ptr< OsqpEigen::Settings > & OsqpEigen::Solver::settings () const
Get the solver settings pointer.
Returns
the pointer to Settings object.
Definition at line 141 of file Solver.cpp.
setWarmStart()
template<typename T , int n, int m>
bool OsqpEigen::Solver::setWarmStart (const Eigen::Matrix< T, n, 1 > & primalVariable, const Eigen::Matrix< T, m, 1 > & dualVariable)
Set the entire.
Parameters
linearConstraintsMatrix is the linear constraint matrix A
Returns
true/false in case of success/failure.
Definition at line 207 of file Solver.tpp.
solve()
bool OsqpEigen::Solver::solve ()
Solve the QP optimization problem.
Returns
true/false in case of success/failure.
Definition at line 106 of file Solver.cpp.
updateBounds() [1/2]
template<int m>
bool OsqpEigen::Solver::updateBounds (Eigen::Matrix< c_float, m, 1 > & lowerBound, Eigen::Matrix< c_float, m, 1 > & upperBound)
Update both upper and lower bounds (size m).
Parameters
lowerBound is the lower bound constraint vector;
upperBound is the upper bound constraint vector.
Note
the elements of the lowerBound and upperBound are not copied inside the library. The user has to guarantee that the lifetime of the objects passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 417 of file Solver.tpp.
updateBounds() [2/2]
bool OsqpEigen::Solver::updateBounds (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> & lowerBound, const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> & upperBound)
Update both upper and lower bounds (size m).
Parameters
lowerBound is the lower bound constraint vector;
upperBound is the upper bound constraint vector.
Note
the elements of the lowerBound and upperBound are not copied inside the library. The user has to guarantee that the lifetime of the objects passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 206 of file Solver.cpp.
updateGradient() [1/2]
template<int n>
bool OsqpEigen::Solver::updateGradient (Eigen::Matrix< c_float, n, 1 > & gradient)
Update the linear part of the cost function (Gradient).
Parameters
gradient is the Gradient vector.
Note
the elements of the gradient are not copied inside the library. The user has to guarantee that the lifetime of the objects passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 358 of file Solver.tpp.
updateGradient() [2/2]
bool OsqpEigen::Solver::updateGradient (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> & gradient)
Update the linear part of the cost function (Gradient).
Parameters
gradient is the Gradient vector.
Note
the elements of the gradient are not copied inside the library. The user has to guarantee that the lifetime of the objects passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 151 of file Solver.cpp.
updateHessianMatrix() [1/2]
template<typename T >
bool OsqpEigen::Solver::updateHessianMatrix (const Eigen::SparseMatrix< T > & hessianMatrix)
Update the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Note
If the sparsity pattern is preserved the matrix is simply update otherwise the entire solver will be reinitialized. In this case the primal and dual variable are copied in the new workspace.
Parameters
hessian is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 444 of file Solver.tpp.
References OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets(), and OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets().
updateHessianMatrix() [2/2]
template<typename Derived >
bool OsqpEigen::Solver::updateHessianMatrix (const Eigen::SparseCompressedBase< Derived > & hessianMatrix)
Update the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Note
If the sparsity pattern is preserved the matrix is simply update otherwise the entire solver will be reinitialized. In this case the primal and dual variable are copied in the new workspace.
Parameters
hessian is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 13 of file Solver.tpp.
References clearSolver(), OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets(), initSolver(), and OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets().
updateLinearConstraintsMatrix() [1/2]
template<typename T >
bool OsqpEigen::Solver::updateLinearConstraintsMatrix (const Eigen::SparseMatrix< T > & linearConstraintsMatrix)
Update the linear constraints matrix (A)
Note
If the sparsity pattern is preserved the matrix is simply update otherwise the entire solver will be reinitialized. In this case the primal and dual variable are copied in the new workspace.
Parameters
linearConstraintsMatrix is the linear constraint matrix A
Returns
true/false in case of success/failure.
Definition at line 542 of file Solver.tpp.
References OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets(), and OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets().
updateLinearConstraintsMatrix() [2/2]
template<typename Derived >
bool OsqpEigen::Solver::updateLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > & linearConstraintsMatrix)
Update the linear constraints matrix (A)
Note
If the sparsity pattern is preserved the matrix is simply update otherwise the entire solver will be reinitialized. In this case the primal and dual variable are copied in the new workspace.
Parameters
linearConstraintsMatrix is the linear constraint matrix A
Returns
true/false in case of success/failure.
Definition at line 111 of file Solver.tpp.
References OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets(), and OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets().
updateLowerBound() [1/2]
template<int m>
bool OsqpEigen::Solver::updateLowerBound (Eigen::Matrix< c_float, m, 1 > & lowerBound)
Update the lower bounds limit (size m).
Parameters
lowerBound is the lower bound constraint vector.
Note
the elements of the lowerBound are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 377 of file Solver.tpp.
updateLowerBound() [2/2]
bool OsqpEigen::Solver::updateLowerBound (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> & lowerBound)
Update the lower bounds limit (size m).
Parameters
lowerBound is the lower bound constraint vector.
Note
the elements of the lowerBound are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 169 of file Solver.cpp.
updateUpperBound() [1/2]
template<int m>
bool OsqpEigen::Solver::updateUpperBound (Eigen::Matrix< c_float, m, 1 > & upperBound)
Update the upper bounds limit (size m).
Parameters
upperBound is the upper bound constraint vector.
Note
the elements of the upperBound are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 397 of file Solver.tpp.
updateUpperBound() [2/2]
bool OsqpEigen::Solver::updateUpperBound (const Eigen::Ref< const Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> & upperBound)
Update the upper bounds limit (size m).
Parameters
upperBound is the upper bound constraint vector.
Note
the elements of the upperBound are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 188 of file Solver.cpp.
The documentation for this class was generated from the following files:
Solver.hpp
Solver.cpp
Solver.tpp