OsqpEigen::Data Class Reference
Data class is a wrapper of the OSQP OSQPData struct.
#include <Data.hpp>
Public Member Functions
Data ()
Constructor.
Data (int n, int m)
Constructor.
~Data ()
Deconstructor.
void clearHessianMatrix ()
Clear the hessian matrix.
void clearLinearConstraintsMatrix ()
Clear the linear constraints matrix.
void setNumberOfVariables (int n)
Set the number of variables.
void setNumberOfConstraints (int m)
Set the number of constraints.
template<typename T >
bool setHessianMatrix (const Eigen::SparseMatrix< T > &hessianMatrix)
Set the quadratic part of the cost function (Hessian).
template<typename Derived >
bool setHessianMatrix (const Eigen::SparseCompressedBase< Derived > &hessianMatrix)
Set the quadratic part of the cost function (Hessian).
template<int n>
bool setGradient (Eigen::Matrix< c_float, n, 1 > &gradientVector)
Set the linear part of the cost function (Gradient).
bool setGradient (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> gradientVector)
Set the linear part of the cost function (Gradient).
template<typename T >
bool setLinearConstraintsMatrix (const Eigen::SparseMatrix< T > &linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
template<typename Derived >
bool setLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > &linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
template<int m>
bool setLowerBound (Eigen::Matrix< c_float, m, 1 > &lowerBoundVector)
Set the array for lower bound (size m).
bool setLowerBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBoundVector)
Set the array for lower bound (size m).
template<int m>
bool setUpperBound (Eigen::Matrix< c_float, m, 1 > &upperBoundVector)
Set the array for upper bound (size m).
bool setUpperBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBoundVector)
Set the array for upper bound (size m).
OSQPData *const & getData () const
Get the OSQPData struct.
bool isSet () const
Verify if all the matrix and vectors are already set.
Detailed Description
Data class is a wrapper of the OSQP OSQPData struct.
Definition at line 28 of file Data.hpp.
Constructor & Destructor Documentation
Data()
OsqpEigen::Data::Data (int n, int m)
Constructor.
Parameters
n is the number of variables;
m is the number of constraints.
Definition at line 28 of file Data.cpp.
References setNumberOfConstraints(), and setNumberOfVariables().
Member Function Documentation
getData()
OSQPData *const & OsqpEigen::Data::getData () const
Get the OSQPData struct.
Returns
a const point to the OSQPData struct.
Definition at line 82 of file Data.cpp.
isSet()
bool OsqpEigen::Data::isSet () const
Verify if all the matrix and vectors are already set.
Returns
true if all the OSQPData struct are set.
Definition at line 87 of file Data.cpp.
setGradient() [1/2]
template<int n>
bool OsqpEigen::Data::setGradient (Eigen::Matrix< c_float, n, 1 > & gradientVector)
Set the linear part of the cost function (Gradient).
Parameters
gradientVector is the Gradient vector.
Note
the elements of the gradient are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 122 of file Data.tpp.
setGradient() [2/2]
bool OsqpEigen::Data::setGradient (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> gradientVector)
Set the linear part of the cost function (Gradient).
Parameters
gradientVector is the Gradient vector.
Note
the elements of the gradient are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 98 of file Data.cpp.
setHessianMatrix() [1/2]
template<typename T >
bool OsqpEigen::Data::setHessianMatrix (const Eigen::SparseMatrix< T > & hessianMatrix)
Set the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Parameters
hessianMatrix is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 11 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix().
setHessianMatrix() [2/2]
template<typename Derived >
bool OsqpEigen::Data::setHessianMatrix (const Eigen::SparseCompressedBase< Derived > & hessianMatrix)
Set the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Parameters
hessianMatrix is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 47 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix().
setLinearConstraintsMatrix() [1/2]
template<typename T >
bool OsqpEigen::Data::setLinearConstraintsMatrix (const Eigen::SparseMatrix< T > & linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
Parameters
linearConstraintsMatrix is the linear constraints matrix A.
Returns
true/false in case of success/failure.
Definition at line 135 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix().
setLinearConstraintsMatrix() [2/2]
template<typename Derived >
bool OsqpEigen::Data::setLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > & linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
Parameters
linearConstraintsMatrix is the linear constraints matrix A.
Returns
true/false in case of success/failure.
Definition at line 81 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix().
setLowerBound() [1/2]
template<int m>
bool OsqpEigen::Data::setLowerBound (Eigen::Matrix< c_float, m, 1 > & lowerBoundVector)
Set the array for lower bound (size m).
Parameters
lowerBoundVector is the lower bound constraint.
Note
the elements of the lowerBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 176 of file Data.tpp.
setLowerBound() [2/2]
bool OsqpEigen::Data::setLowerBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBoundVector)
Set the array for lower bound (size m).
Parameters
lowerBoundVector is the lower bound constraint.
Note
the elements of the lowerBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 110 of file Data.cpp.
setNumberOfConstraints()
void OsqpEigen::Data::setNumberOfConstraints (int m)
Set the number of constraints.
Parameters
m is the number of constraints.
Definition at line 76 of file Data.cpp.
Referenced by Data().
setNumberOfVariables()
void OsqpEigen::Data::setNumberOfVariables (int n)
Set the number of variables.
Parameters
n is the number of variables.
Definition at line 70 of file Data.cpp.
Referenced by Data().
setUpperBound() [1/2]
template<int m>
bool OsqpEigen::Data::setUpperBound (Eigen::Matrix< c_float, m, 1 > & upperBoundVector)
Set the array for upper bound (size m).
Parameters
upperBoundVector is the upper bound constraint.
Note
the elements of the upperBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 189 of file Data.tpp.
setUpperBound() [2/2]
bool OsqpEigen::Data::setUpperBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBoundVector)
Set the array for upper bound (size m).
Parameters
upperBoundVector is the upper bound constraint.
Note
the elements of the upperBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 122 of file Data.cpp.
The documentation for this class was generated from the following files:
Data.hpp
Data.cpp
Data.tpp